[2025-06-14T19:19:17.155+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping_autopia_dag.trigger_procesamiento manual__2025-06-14T19:15:08.479063+00:00 [queued]>
[2025-06-14T19:19:17.167+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping_autopia_dag.trigger_procesamiento manual__2025-06-14T19:15:08.479063+00:00 [queued]>
[2025-06-14T19:19:17.167+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-06-14T19:19:17.194+0000] {taskinstance.py:2191} INFO - Executing <Task(TriggerDagRunOperator): trigger_procesamiento> on 2025-06-14 19:15:08.479063+00:00
[2025-06-14T19:19:17.203+0000] {standard_task_runner.py:60} INFO - Started process 1129 to run task
[2025-06-14T19:19:17.210+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'scraping_autopia_dag', 'trigger_procesamiento', 'manual__2025-06-14T19:15:08.479063+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/scraping_autopia_dag.py', '--cfg-path', '/tmp/tmpxo0yi67e']
[2025-06-14T19:19:17.215+0000] {standard_task_runner.py:88} INFO - Job 117: Subtask trigger_procesamiento
[2025-06-14T19:19:17.299+0000] {task_command.py:423} INFO - Running <TaskInstance: scraping_autopia_dag.trigger_procesamiento manual__2025-06-14T19:15:08.479063+00:00 [running]> on host 15346582a165
[2025-06-14T19:19:17.445+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping_autopia_dag' AIRFLOW_CTX_TASK_ID='trigger_procesamiento' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T19:15:08.479063+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T19:15:08.479063+00:00'
[2025-06-14T19:19:23.348+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:79 AirflowProviderDeprecationWarning: This DataprocLink is deprecated.
[2025-06-14T19:19:23.353+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:128 AirflowProviderDeprecationWarning: This DataprocListLink is deprecated.
[2025-06-14T19:19:29.053+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:20:29.453+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:21:29.477+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:22:29.498+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:23:29.582+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:24:29.627+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:25:29.683+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:26:29.778+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:27:29.855+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:28:29.885+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:29:29.949+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:30:30.038+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:31:30.139+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:32:30.280+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:33:30.388+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:34:30.487+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:35:30.579+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:36:30.682+0000] {trigger_dagrun.py:210} INFO - Waiting for procesamiento_datos_autopia_dag on 2025-06-14 19:19:17.446593+00:00 to become allowed state ['success'] ...
[2025-06-14T19:37:30.854+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 221, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: procesamiento_datos_autopia_dag failed with failed states failed
[2025-06-14T19:37:30.868+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=scraping_autopia_dag, task_id=trigger_procesamiento, execution_date=20250614T191508, start_date=20250614T191917, end_date=20250614T193730
[2025-06-14T19:37:30.981+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 117 for task trigger_procesamiento (procesamiento_datos_autopia_dag failed with failed states failed; 1129)
[2025-06-14T19:37:31.084+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-14T19:37:31.133+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
