[2025-06-21T12:53:43.630+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-17T21:00:00+00:00 [queued]>
[2025-06-21T12:53:43.655+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-17T21:00:00+00:00 [queued]>
[2025-06-21T12:53:43.655+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-21T12:53:43.724+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): entrenar_y_promover> on 2025-06-17 21:00:00+00:00
[2025-06-21T12:53:43.734+0000] {standard_task_runner.py:60} INFO - Started process 203 to run task
[2025-06-21T12:53:43.750+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'entrenamiento_modelos_regresion', 'entrenar_y_promover', 'scheduled__2025-06-17T21:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/entrenamiento_modelos_regresion_dag.py', '--cfg-path', '/tmp/tmpi7nmw5ni']
[2025-06-21T12:53:43.760+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask entrenar_y_promover
[2025-06-21T12:53:44.012+0000] {task_command.py:423} INFO - Running <TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-17T21:00:00+00:00 [running]> on host b043483ba5b8
[2025-06-21T12:53:44.831+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fede' AIRFLOW_CTX_DAG_ID='entrenamiento_modelos_regresion' AIRFLOW_CTX_TASK_ID='entrenar_y_promover' AIRFLOW_CTX_EXECUTION_DATE='2025-06-17T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-17T21:00:00+00:00'
[2025-06-21T12:53:56.078+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:59 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-21T12:53:56.105+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:62 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-21T12:53:56.109+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:64 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-21T12:53:56.112+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:65 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-21T12:53:59.782+0000] {connectionpool.py:824} WARNING - Retrying (JitteredRetry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x726d513f93d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=entrenamiento_orquestado
[2025-06-21T12:54:05.259+0000] {connectionpool.py:824} WARNING - Retrying (JitteredRetry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x726d5139a220>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=entrenamiento_orquestado
[2025-06-21T12:54:16.829+0000] {connectionpool.py:824} WARNING - Retrying (JitteredRetry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x726d5139aee0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=entrenamiento_orquestado
[2025-06-21T12:54:34.275+0000] {connectionpool.py:824} WARNING - Retrying (JitteredRetry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x726d51356070>: Failed to establish a new connection: [Errno -2] Name or service not known')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=entrenamiento_orquestado
[2025-06-21T12:55:04.007+0000] {connectionpool.py:824} WARNING - Retrying (JitteredRetry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x726d51356100>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=entrenamiento_orquestado
[2025-06-21T12:55:04.326+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:04 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-21T12:55:12.629+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-21T12:55:12.955+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:12 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest at: http://mlflow:5000/#/experiments/1/runs/e8ae0123175f4a438723c65bd47b6adf.
[2025-06-21T12:55:12.955+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:12 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-21T12:55:17.195+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-21T12:55:17.895+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:17 INFO mlflow.tracking._tracking_service.client: üèÉ View run GradientBoosting at: http://mlflow:5000/#/experiments/1/runs/715707a963d1424ab1e782a9085fff3d.
[2025-06-21T12:55:17.895+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:17 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-21T12:55:21.431+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-21T12:55:21.520+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:21 INFO mlflow.tracking._tracking_service.client: üèÉ View run SVR at: http://mlflow:5000/#/experiments/1/runs/5d2b5ef372e2472b875381a6005902b3.
[2025-06-21T12:55:21.521+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:21 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-21T12:55:21.606+0000] {logging_mixin.py:188} WARNING - Registered model 'mejor_modelo_orquestado' already exists. Creating a new version of this model...
[2025-06-21T12:55:21.731+0000] {logging_mixin.py:188} WARNING - 2025/06/21 12:55:21 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: mejor_modelo_orquestado, version 2
[2025-06-21T12:55:21.732+0000] {logging_mixin.py:188} WARNING - Created version '2' of model 'mejor_modelo_orquestado'.
[2025-06-21T12:55:21.734+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:111 FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-21T12:55:21.870+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:122 FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-21T12:55:21.903+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:115 FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-21T12:55:21.930+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-21T12:55:21.954+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=entrenamiento_modelos_regresion, task_id=entrenar_y_promover, execution_date=20250617T210000, start_date=20250621T125343, end_date=20250621T125521
[2025-06-21T12:55:22.047+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-21T12:55:22.080+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
