[2025-06-14T20:15:51.650+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: procesamiento_datos_autopia_dag.trigger_entrenamiento manual__2025-06-14T20:14:22.379058+00:00 [queued]>
[2025-06-14T20:15:51.662+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: procesamiento_datos_autopia_dag.trigger_entrenamiento manual__2025-06-14T20:14:22.379058+00:00 [queued]>
[2025-06-14T20:15:51.662+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-14T20:15:51.682+0000] {taskinstance.py:2191} INFO - Executing <Task(TriggerDagRunOperator): trigger_entrenamiento> on 2025-06-14 20:14:22.379058+00:00
[2025-06-14T20:15:51.690+0000] {standard_task_runner.py:60} INFO - Started process 1108 to run task
[2025-06-14T20:15:51.694+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'procesamiento_datos_autopia_dag', 'trigger_entrenamiento', 'manual__2025-06-14T20:14:22.379058+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/procesamiento_datos_autopia_dag.py', '--cfg-path', '/tmp/tmplgorhi70']
[2025-06-14T20:15:51.697+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask trigger_entrenamiento
[2025-06-14T20:15:51.779+0000] {task_command.py:423} INFO - Running <TaskInstance: procesamiento_datos_autopia_dag.trigger_entrenamiento manual__2025-06-14T20:14:22.379058+00:00 [running]> on host b32a9208912d
[2025-06-14T20:15:51.889+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fede' AIRFLOW_CTX_DAG_ID='procesamiento_datos_autopia_dag' AIRFLOW_CTX_TASK_ID='trigger_entrenamiento' AIRFLOW_CTX_EXECUTION_DATE='2025-06-14T20:14:22.379058+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-14T20:14:22.379058+00:00'
[2025-06-14T20:15:52.774+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:79 AirflowProviderDeprecationWarning: This DataprocLink is deprecated.
[2025-06-14T20:15:52.775+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/links/dataproc.py:128 AirflowProviderDeprecationWarning: This DataprocListLink is deprecated.
[2025-06-14T20:15:53.592+0000] {trigger_dagrun.py:210} INFO - Waiting for entrenamiento_modelos_regresion on 2025-06-14 20:15:51.890294+00:00 to become allowed state ['success'] ...
[2025-06-14T20:16:53.662+0000] {trigger_dagrun.py:210} INFO - Waiting for entrenamiento_modelos_regresion on 2025-06-14 20:15:51.890294+00:00 to become allowed state ['success'] ...
[2025-06-14T20:17:53.749+0000] {trigger_dagrun.py:210} INFO - Waiting for entrenamiento_modelos_regresion on 2025-06-14 20:15:51.890294+00:00 to become allowed state ['success'] ...
[2025-06-14T20:18:53.808+0000] {trigger_dagrun.py:210} INFO - Waiting for entrenamiento_modelos_regresion on 2025-06-14 20:15:51.890294+00:00 to become allowed state ['success'] ...
[2025-06-14T20:19:53.861+0000] {trigger_dagrun.py:210} INFO - Waiting for entrenamiento_modelos_regresion on 2025-06-14 20:15:51.890294+00:00 to become allowed state ['success'] ...
[2025-06-14T20:20:53.949+0000] {trigger_dagrun.py:210} INFO - Waiting for entrenamiento_modelos_regresion on 2025-06-14 20:15:51.890294+00:00 to become allowed state ['success'] ...
[2025-06-14T20:21:46.948+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-06-14T20:21:46.957+0000] {process_utils.py:131} INFO - Sending 15 to group 1108. PIDs of all processes in the group: [1108]
[2025-06-14T20:21:46.958+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1108
[2025-06-14T20:21:46.973+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-14T20:21:47.049+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 216, in execute
    time.sleep(self.poke_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-06-14T20:21:47.059+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=procesamiento_datos_autopia_dag, task_id=trigger_entrenamiento, execution_date=20250614T201422, start_date=20250614T201551, end_date=20250614T202147
[2025-06-14T20:21:47.109+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task trigger_entrenamiento (Task received SIGTERM signal; 1108)
[2025-06-14T20:21:47.225+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1108, status='terminated', exitcode=1, started='20:15:50') (1108) terminated with exit code 1
[2025-06-14T20:21:47.230+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
[2025-06-14T20:21:47.296+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
