[2025-05-25T18:05:11.241+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover manual__2025-05-25T18:05:11.074937+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
