[2025-06-14T17:39:30.927+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-12T21:00:00+00:00 [queued]>
[2025-06-14T17:39:30.944+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-12T21:00:00+00:00 [queued]>
[2025-06-14T17:39:30.944+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-14T17:39:30.971+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): entrenar_y_promover> on 2025-06-12 21:00:00+00:00
[2025-06-14T17:39:30.979+0000] {standard_task_runner.py:60} INFO - Started process 203 to run task
[2025-06-14T17:39:30.987+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'entrenamiento_modelos_regresion', 'entrenar_y_promover', 'scheduled__2025-06-12T21:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/entrenamiento_modelos_regresion_dag.py', '--cfg-path', '/tmp/tmpiv02qzqp']
[2025-06-14T17:39:30.991+0000] {standard_task_runner.py:88} INFO - Job 105: Subtask entrenar_y_promover
[2025-06-14T17:39:31.116+0000] {task_command.py:423} INFO - Running <TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-12T21:00:00+00:00 [running]> on host 1a7eb03353f3
[2025-06-14T17:39:31.310+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fede' AIRFLOW_CTX_DAG_ID='entrenamiento_modelos_regresion' AIRFLOW_CTX_TASK_ID='entrenar_y_promover' AIRFLOW_CTX_EXECUTION_DATE='2025-06-12T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-12T21:00:00+00:00'
[2025-06-14T17:39:35.403+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:55 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-14T17:39:35.422+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:58 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-14T17:39:35.425+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:60 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-14T17:39:35.427+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:61 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-14T17:39:35.704+0000] {logging_mixin.py:188} WARNING - 2025/06/14 17:39:35 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-14T17:39:44.956+0000] {logging_mixin.py:188} WARNING - 2025/06/14 17:39:44 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-14T17:39:45.074+0000] {logging_mixin.py:188} WARNING - 2025/06/14 17:39:45 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest at: http://mlflow:5000/#/experiments/1/runs/48f901ede880431c92979d6c310d8abb.
[2025-06-14T17:39:45.075+0000] {logging_mixin.py:188} WARNING - 2025/06/14 17:39:45 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-14T17:39:45.136+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/entrenamiento_modelos_regresion_dag.py", line 101, in entrenar_y_promover
    mlflow.sklearn.log_model(modelo, "modelo")
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/sklearn/__init__.py", line 413, in log_model
    return Model.log(
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/models/model.py", line 744, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 1170, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1977, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 874, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 66, in log_artifacts
    mkdir(artifact_dir)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 211, in mkdir
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/utils/file_utils.py", line 208, in mkdir
    os.makedirs(target, exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mlflow/mlruns/1/48f901ede880431c92979d6c310d8abb'
[2025-06-14T17:39:45.171+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=entrenamiento_modelos_regresion, task_id=entrenar_y_promover, execution_date=20250612T210000, start_date=20250614T173930, end_date=20250614T173945
[2025-06-14T17:39:45.193+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 105 for task entrenar_y_promover ([Errno 13] Permission denied: '/mlflow/mlruns/1/48f901ede880431c92979d6c310d8abb'; 203)
[2025-06-14T17:39:45.291+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-06-14T17:39:45.357+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-14T20:16:54.270+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-12T21:00:00+00:00 [queued]>
[2025-06-14T20:16:54.285+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-12T21:00:00+00:00 [queued]>
[2025-06-14T20:16:54.286+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-06-14T20:16:54.303+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): entrenar_y_promover> on 2025-06-12 21:00:00+00:00
[2025-06-14T20:16:54.309+0000] {standard_task_runner.py:60} INFO - Started process 1186 to run task
[2025-06-14T20:16:54.316+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'entrenamiento_modelos_regresion', 'entrenar_y_promover', 'scheduled__2025-06-12T21:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/entrenamiento_modelos_regresion_dag.py', '--cfg-path', '/tmp/tmp0afmhko7']
[2025-06-14T20:16:54.319+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask entrenar_y_promover
[2025-06-14T20:16:54.414+0000] {task_command.py:423} INFO - Running <TaskInstance: entrenamiento_modelos_regresion.entrenar_y_promover scheduled__2025-06-12T21:00:00+00:00 [running]> on host b32a9208912d
[2025-06-14T20:16:54.565+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fede' AIRFLOW_CTX_DAG_ID='entrenamiento_modelos_regresion' AIRFLOW_CTX_TASK_ID='entrenar_y_promover' AIRFLOW_CTX_EXECUTION_DATE='2025-06-12T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-12T21:00:00+00:00'
[2025-06-14T20:16:59.572+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:55 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-14T20:16:59.589+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:58 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-14T20:16:59.591+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:60 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-14T20:16:59.593+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:61 SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-06-14T20:16:59.788+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:16:59 INFO mlflow.tracking.fluent: Experiment with name 'entrenamiento_orquestado' does not exist. Creating a new experiment.
[2025-06-14T20:16:59.952+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:16:59 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-14T20:17:06.562+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-14T20:17:06.828+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:06 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest at: http://mlflow:5000/#/experiments/1/runs/c3c29d7bbb7e42dca62e1e3570f5fcf5.
[2025-06-14T20:17:06.829+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:06 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-14T20:17:10.077+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:10 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-14T20:17:10.356+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:10 INFO mlflow.tracking._tracking_service.client: üèÉ View run CatBoost at: http://mlflow:5000/#/experiments/1/runs/82fdcb0519de4ccd8afe6d00b1d8db44.
[2025-06-14T20:17:10.356+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:10 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-14T20:17:12.724+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-06-14T20:17:12.797+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:12 INFO mlflow.tracking._tracking_service.client: üèÉ View run SVR at: http://mlflow:5000/#/experiments/1/runs/bd7d121cd2384104835120a5b7de6e60.
[2025-06-14T20:17:12.798+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:12 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-06-14T20:17:12.854+0000] {logging_mixin.py:188} WARNING - Successfully registered model 'mejor_modelo_orquestado'.
[2025-06-14T20:17:12.902+0000] {logging_mixin.py:188} WARNING - 2025/06/14 20:17:12 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: mejor_modelo_orquestado, version 1
[2025-06-14T20:17:12.902+0000] {logging_mixin.py:188} WARNING - Created version '1' of model 'mejor_modelo_orquestado'.
[2025-06-14T20:17:12.903+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:109 FutureWarning: ``mlflow.tracking.client.MlflowClient.get_latest_versions`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-14T20:17:13.267+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/entrenamiento_modelos_regresion_dag.py:113 FutureWarning: ``mlflow.tracking.client.MlflowClient.transition_model_version_stage`` is deprecated since 2.9.0. Model registry stages will be removed in a future major release. To learn more about the deprecation of model registry stages, see our migration guide here: https://mlflow.org/docs/latest/model-registry.html#migrating-from-stages
[2025-06-14T20:17:13.295+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-14T20:17:13.315+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=entrenamiento_modelos_regresion, task_id=entrenar_y_promover, execution_date=20250612T210000, start_date=20250614T201654, end_date=20250614T201713
[2025-06-14T20:17:13.404+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-14T20:17:13.428+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
