[2025-05-31T15:19:31.658+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping_autopia_dag.scrapear_datos_autopia manual__2025-05-31T15:19:29.493187+00:00 [queued]>
[2025-05-31T15:19:31.665+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping_autopia_dag.scrapear_datos_autopia manual__2025-05-31T15:19:29.493187+00:00 [queued]>
[2025-05-31T15:19:31.666+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-05-31T15:19:31.679+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): scrapear_datos_autopia> on 2025-05-31 15:19:29.493187+00:00
[2025-05-31T15:19:31.685+0000] {standard_task_runner.py:60} INFO - Started process 293 to run task
[2025-05-31T15:19:31.689+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'scraping_autopia_dag', 'scrapear_datos_autopia', 'manual__2025-05-31T15:19:29.493187+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/scraping_autopia_dag.py', '--cfg-path', '/tmp/tmpatgm08g1']
[2025-05-31T15:19:31.692+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask scrapear_datos_autopia
[2025-05-31T15:19:31.768+0000] {task_command.py:423} INFO - Running <TaskInstance: scraping_autopia_dag.scrapear_datos_autopia manual__2025-05-31T15:19:29.493187+00:00 [running]> on host b424c00db827
[2025-05-31T15:19:31.876+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping_autopia_dag' AIRFLOW_CTX_TASK_ID='scrapear_datos_autopia' AIRFLOW_CTX_EXECUTION_DATE='2025-05-31T15:19:29.493187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-31T15:19:29.493187+00:00'
[2025-05-31T15:46:31.574+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-05-31T15:46:31.753+0000] {process_utils.py:131} INFO - Sending 15 to group 293. PIDs of all processes in the group: [294, 306, 308, 309, 339, 9004, 9652, 322, 293]
[2025-05-31T15:46:31.754+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 293
[2025-05-31T15:46:31.758+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-31T15:46:31.968+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=308, status='terminated', started='15:19:33') (308) terminated with exit code None
[2025-05-31T15:46:31.969+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=309, status='terminated', started='15:19:33') (309) terminated with exit code None
[2025-05-31T15:46:31.970+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=339, status='terminated', started='15:19:33') (339) terminated with exit code None
[2025-05-31T15:46:31.970+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9004, status='terminated', started='15:45:43') (9004) terminated with exit code None
[2025-05-31T15:46:31.971+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=9652, status='terminated', started='15:48:01') (9652) terminated with exit code None
[2025-05-31T15:46:31.972+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=306, status='terminated', started='15:19:32') (306) terminated with exit code None
[2025-05-31T15:46:32.115+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=294, status='terminated', started='15:19:31') (294) terminated with exit code None
[2025-05-31T15:46:32.117+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=322, status='terminated', started='15:19:33') (322) terminated with exit code None
[2025-05-31T15:46:32.142+0000] {base_events.py:1707} ERROR - Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
[2025-05-31T15:46:32.151+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/scraping_autopia.py", line 79, in run_scraper
    page_number = 1
  File "/opt/airflow/dags/utils/scraping_autopia.py", line 55, in scrape_page
    model = " ".join(model_parts)
  File "/home/airflow/.local/lib/python3.8/site-packages/playwright/sync_api/_generated.py", line 9002, in goto
    self._sync(
  File "/home/airflow/.local/lib/python3.8/site-packages/playwright/_impl/_sync_base.py", line 113, in _sync
    self._dispatcher_fiber.switch()
  File "/home/airflow/.local/lib/python3.8/site-packages/playwright/sync_api/_context_manager.py", line 56, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.8/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-05-31T15:46:32.159+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=scraping_autopia_dag, task_id=scrapear_datos_autopia, execution_date=20250531T151929, start_date=20250531T151931, end_date=20250531T154632
[2025-05-31T15:46:32.199+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task scrapear_datos_autopia (Task received SIGTERM signal; 293)
[2025-05-31T15:46:32.258+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=293, status='terminated', exitcode=1, started='15:19:31') (293) terminated with exit code 1
[2025-05-31T15:46:32.258+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
[2025-05-31T15:46:32.292+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
